-- Realtime Chatroom table setup
-- Run this in Supabase SQL Editor.

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  room text not null default 'main-room',
  user_name text not null check (char_length(user_name) <= 40),
  content text not null check (char_length(content) <= 4000),
  is_ai boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;

-- Demo policies: anyone with anon key can read and insert chat messages.
-- For production, replace these with auth-based policies.
drop policy if exists "Anyone can read chat messages" on public.messages;
create policy "Anyone can read chat messages"
on public.messages
for select
to anon, authenticated
using (true);

drop policy if exists "Anyone can insert chat messages" on public.messages;
create policy "Anyone can insert chat messages"
on public.messages
for insert
to anon, authenticated
with check (true);

-- Enable Supabase Realtime for this table.
alter publication supabase_realtime add table public.messages;
